export const MASTERY_COMPLETED = [
  "MK1-Paris",
  "Lato",
  "Excalibur",
  "Skana",
  "Grakata",
  "Kunai",
  "Taxon",
  "Artax",
  "Orthos",
  "<ARCHWING> Odonata",
  "Imperator",
  "<ARCHWING> Veritux",
  "Boltor",
  "Lex",
  "Galatine",
  "Frost",
  "Gorgon",
  "Furis",
  "Carrier",
  "Sweeper",
  "Vulkar",
  "Cronus",
  "Mag",
  "Braton",
  "Viper",
  "Dethcube",
  "Deth Machine Rifle",
  "Volt",
  "Amphis",
  "Soma",
  "Cestra",
  "Huras Kubrow",
  "Tigris",
  "Orthos Prime",
  "Twin Vipers",
  "Amprex",
  "Shade",
  "Burst Laser",
  "Ignis Wraith",
  "Paris Prime",
  "Carrier Prime",
  "Sweeper Prime",
  "Nekros Prime",
  "Nikana Prime",
  "Dark Sword",
  "Aklato",
  "Dread",
  "Oberon",
  "Ether Daggers",
  "Penta",
  "Soma Prime",
  "Akstiletto Prime",
  "Jaw Sword",
  "Ash Prime",
  "Glaive",
  "Lex Prime",
  "Lecta",
  "Ember",
  "Latron",
  "Broken War",
  "Kraken",
  "Broken Scepter",
  "Gammacor",
  "Helios Prime",
  "Deconstructor Prime",
  "Boar",
  "Saryn Prime",
  "Twin Grakatas",
  "Heat Sword",
  "Pyrana",
  "Drakgoon",
  "Heat Dagger",
  "Hikou",
  "Burston",
  "Spira",
  "Fang",
  "Cernos",
  "Sybaris",
  "Kestrel",
  "Vectis Prime",
  "Banshee",
  "Plasma Sword",
  "Braton Prime",
  "Boltor Prime",
  "Pangolin Sword",
  "Zarr",
  "Aklex Prime",
  "Atterax",
  "Supra",
  "Twin Gremlins",
  "Trinity",
  "Quanta",
  "Mire",
  "Burston Prime",
  "Fragor",
  "Banshee Prime",
  "Bo",
  "Volt Prime",
  "Karak",
  "Stug",
  "Tetra",
  "Despair",
  "Tipedo",
  "Hikou Prime",
  "War",
  "Frost Prime",
  "Phage",
  "Aklex",
  "Fragor Prime",
  "Loki",
  "Bronco",
  "Fang Prime",
  "Cernos Prime",
  "Akbronco",
  "Galatine Prime",
  "Rhino",
  "Tigris Prime",
  "Vaykor Hek",
  "Mirage",
  "Telos Boltace",
  "Opticor",
  "Rhino Prime",
  "Silva & Aegis Prime",
  "Boar Prime",
  "Mag Prime",
  "Sicarus",
  "Nova",
  "Guandao",
  "Azima",
  "Trinity Prime",
  "Excalibur Umbra",
  "Skiajati",
  "Atomos",
  "Afuris",
  "Ankyros",
  "Ballistica",
  "Dual Skana",
  "Loki Prime",
  "Akzani",
  "Astilla",
  "Angstrum",
  "Hek",
  "Bolto",
  "Hind",
  "Magnus",
  "Harpak",
  "Akbolto",
  "Nikana",
  "Vasto",
  "Sobek",
  "Ember Prime",
  "Kronen",
  "Zakti",
  "Tiberon",
  "Mesa",
  "Akjagara",
  "Dual Zoren",
  "Stradavar",
  "Akvasto",
  "Krohkur",
  "Mutalist Cernos",
  "Kohm",
  "Akmagnus",
  "Lanka",
  "Akstiletto",
  "Boltace",
  "Paris",
  "Twin Rogga",
  "Saryn",
  "Rubico",
  "Aksomati",
  "Anku",
  "Tonkor",
  "Kohmak",
  "Volnus",
  "Arca Plasmor",
  "Secura Dual Cestra",
  "Scourge",
  "Corinth",
  "Tysis",
  "Dual Heat Swords",
  "Chroma",
  "Dual Ether",
  "Inaros",
  "Limbo",
  "Dual Keres",
  "Dragon Nikana",
  "Ether Reaper",
  "Ether Sword",
  "Gram",
  "Nezha",
  "Hirudo",
  "Valkyr",
  "Gunsen",
  "Furax",
  "Zephyr",
  "Twin Krohkur",
  "Karyst",
  "Secura Lecta",
  "Nyx",
  "Wukong",
  "Magistar",
  "Kama",
  "Machete",
  "<ARCHWING> Itzal",
  "Zylok",
  "Akbolto Prime",
  "Prisma Shade",
  "Prisma Burst Laser",
  "Telos Boltor",
  "Twin Kohmak",
  "Hydroid",
  "Dual Kamas",
  "Sancti Tigris",
  "Bronco Prime",
  "Ankyros Prime",
  "Secura Penta",
  "Ballistica Prime",
  "Dakra Prime",
  "Shwaak Prism",
  "Supra Vandal",
  "Plague Kripath",
  "Tiberon Prime",
  "Dex Dakra",
  "Pyrana Prime",
  "Kogake",
  "Djinn",
  "Equinox",
  "Stinger",
  "Akbronco Prime",
  "Kronen Prime",
  "Helios",
  "Deconstructor",
  "Dex Sybaris",
  "Dex Furis",
  "Nova Prime",
  "Adarza Kavat",
  "Prova Vandal",
  "Vaykor Marelok",
  "Quanta Vandal",
  "Sancti Magistar",
  "Sancti Castanas",
  "Arca Scisco",
  "Titania Prime",
  "Castanas",
  "Hydroid Prime",
  "Venka Prime",
  "Mirage Prime",
  "Dual Cestra",
  "Synapse",
  "Scindo Prime",
  "Vastilok",
  "Dual Toxocyst",
  "Sybaris Prime",
  "Limbo Prime",
  "Vericres",
  "Fusilai",
  "Arca Titron",
  "Attica",
  "Knell",
  "Zephyr Prime",
  "Ignis",
  "Dual Cleavers",
  "Marelok",
  "Cassowar",
  "Baza",
  "Gara",
  "Buzlok",
  "Dual Raza",
  "Pandero",
  "Revenant",
  "Spectra",
  "Daikyu",
  "Endura",
  "Opticor Vandal",
  "Nyx Prime",
  "Helminth Charger",
  "Convectrix",
  "Halikar",
  "Hystrix",
  "Dera",
  "Kulstar",
  "Gazal Machete",
  "Styanax",
  "Ferrox",
  "Jat Kittag",
  "Nukor",
  "Titania",
  "Grinlok",
  "Jat Kusar",
  "Pox",
  "Vauban",
  "Flux Rifle",
  "Seer",
  "Kesheg",
  "Glaxion",
  "Lacera",
  "Talons",
  "Sonicor",
  "Nagantaka",
  "Nami Solo",
  "Lesion",
  "Nami Skyla",
  "Ogris",
  "Stubba",
  "Ninkondi",
  "Obex",
  "Panthera",
  "Quartakk",
  "Ripkas",
  "Prova",
  "Phantasma",
  "Serro",
  "Snipetron",
  "Veldt",
  "Tonbo",
  "Tenora",
  "Scindo",
  "Sarpa",
  "Vectis",
  "Scoliac",
  "Torid",
  "Redeemer",
  "Tekko",
  "Sydon",
  "Silva & Aegis",
  "Twin Basolk",
  "Venka",
];
